@startuml
'https://plantuml.com/class-diagram



class ReactionInfo {
+ quantityMade
+ reactionInputs
}

-class StoichDoer {
+leastRequiredOreForNFuel(N)
- currentState
- balance()
}

interface IReactionInfo {
+getQuantityOfChemicalMadeByOneReaction(String chemical) -> Integer
+getInputsForChemical(String chemical) -> Map<String, Integer>
}

interface IDay14 {
+leastOreRequiredToMakeOneFuel(String reactionsFileName) -> Long
+mostFuelForOneTrillionOre(String reactionsFileName) -> Long

}

interface Day14 {
-readIn(fileName)
-mostFuelCanMakeWithNOre(N)
-leastRequiredOreForNFuel(N)

}

Class ChemicalEnvironment {
}


IDay14 <|.. Day14
Day14 -> ChemicalEnvironment
ChemicalEnvironment *- IReactionInfo
IReactionInfo <|.. ReactionInfo



Day14::leastRequiredOreForNFuel +-StoichDoer

@enduml