@startuml
'https://plantuml.com/class-diagram



class ReactionInfo {
+ quantityMade
+ reactionInputs
}

-class StoichDoer {
+ leastRequiredOreForNFuel(N)
- currentState
- balance()
}

interface IReactionInfo {
+ getQuantityMade()
+ getReactionInputs()
}

interface Day14 {
+leastRequiredOreForOneFuel(fileName)
+mostFuelCanMakeWithTrillionOre(fileName)

}

class Day14Impl {
-readIn(fileName)
-mostFuelCanMakeWithNOre(N)
-leastRequiredOreForNFuel(N)

}



Day14 <|.. Day14Impl


ReactionInfo <-* Day14Impl
Day14Impl::leastRequiredOreForNFuel +-StoichDoer

@enduml