@startuml
'https://plantuml.com/class-diagram

interface Day6 {
+numScanned
+{abstract} findStepsUntilLastNAllDiff()
}

interface IDay6Helper {
+scanNextChar()
+getCharScannedXAgo()
}

Day6 *- IDay6Helper

IDay6Helper <|-- Day6Helper1
IDay6Helper <|-- Day6Helper2

@enduml